[project]
name = "claude-codex-adversarial-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.68.0",
    "click>=8.3.0",
    "openai>=1.108.1",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
]
